<!--
\usepackage[utf8]{inputenc}
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Motivation and Use of Rhtslib}
-->

# Motivation and Use of Rhtslib

- Authors: [Nathaniel Hayden](mailto:nhayden@fredhutch.org), [Martin Morgan](mailto:mtmorgan@fhcrc.org)
- Modification date: 20 February, 2015

This package provides a compiled version of the C
[`htslib`](http://www.htslib.org/) for high-throughput seqeunce
analysis. It is primary useful to developers of other R packages who
want to use the htslib facilities in the C code of their own packages.

## Motivation

There are several advantages to using `Rhtslib`, rather than requiring
an explict user system dependency on `htslib` directly.

- Using `Rhtslib` means that your users (who are not always
  sophisticated system administrators) do not need to manually install
  their own library.
- Your application uses a defined version of `htslib`, so that you as
  a developer can rely on presence of specific features (and bugs!)
  rather than writing code to manage different library versions.
  
## Use

Packages with C code should create a file `src/Makevars` with the
following lines

    PKG_LIBS+=$(shell echo 'Rhtslib::pkgconfig("PKG_LIBS")'|\
        "${R_HOME}/bin/R" --vanilla --slave)

and mention Rhtslib in the `LinkingTo` field of the DESCRIPTION file,
e.g.,

    LinkingTo: Rhtslib

If LinkingTo is not available to you, add to the `src/Makevars` file
the following lines

    PKG_CPPFLAGS+=$(shell echo 'Rhtslib::pkgconfig("PKG_CPPFLAGS")'|\
        "${R_HOME}/bin/R" --vanilla --slave)
    
In C or C++ code files, use standard techniques, e.g., `#include
"hts.h"`. Header files are available for perusal at

```{R headers}
system.file(package="Rhtslib", "include")
```

## Implementation notes

The procedure above links to the static library version of the htslib
library. This will work on Linux, Mac OSX, and Windows, but some
tweaks may be needed on other platforms; please notify
[me](mailto:nhayden@fredhutch.org) of incompatibilities.
